### OpenCV course tutorial: https://www.youtube.com/watch?v=oXlwWbU8l2o&ab_channel=freeCodeCamp.org
- draw images on a frame (e.g. bounding box)
- apply blur on images to reduce noise
- edge cascade
    - find edges in image
    - as blur goes up, edges goes down

In [1]:
# stack greyscale images: np.stack((test,) * 3, axis=-1)
import tensorflow

# blur
blur = cv.GaussianBlur(img, (7.,7), cv.BORDER_DEFAULT)
cv.imshow('Blur', blur)

# edge cascade
canny = cv.Canny(img, 125, 175)
cv.imshow('Canny Edges', canny)

# dilating the image
dilated = cv.dilate(canny, (3,3), iterations=1)
cv.imshow('Dilated', dilated)

# eroding
eroded = cv.erode(dilated, (3,3), iterations=1)

# resize
resized = cv.resize(img, (500,500), interpolation=cv.INTER_AREA)
cv.imshow('Resized', resized)

# cropping
cropped = img[50:200, 200:400]
cv.imshow('Cropped', cropped)

cv.waitKey(0)

In [28]:
c[a<0] = b[a<0] + a[a<0]
print(c)

c[a<0] = b[a<0] + a[a<0]
print(c)

[[ 0.  0.  0.]
 [18.  0.  0.]
 [ 0. 12.  0.]]
[[ 0.  0.  0.]
 [18.  0.  0.]
 [ 0. 12.  0.]]
